package jugador;

public enum EstadoJugador {
	INICIAL,
	TALADRANDO_ABAJO_INICIO,
	TALADRANDO_ABAJO_FULL,
	TALADRANDO_DERECHA_INICIO,
	TALADRANDO_DERECHA_FULL,
	TALADRANDO_IZQUIERDA_INICIO,
	TALADRANDO_IZQUIERDA_FULL;
}
